### Test ping endpoint
GET http://localhost:8080/ping HTTP/1.1

### Test CreateUser 
POST http://localhost:8081/api/v1/users HTTP/1.1
Content-Type: application/json

{   "name": "vuinguyen2",
    "email": "vuinguyen@example.com",
    "password": "Vixuancu22012004@"
}

### Test login with invalid credentials
POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "wrongpass"
}

### Test login with missing fields
POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@example.com"
}