// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Message struct {
	MessageID        int64     `json:"message_id"`
	RoomID           int64     `json:"room_id"`
	UserUuid         uuid.UUID `json:"user_uuid"`
	Content          string    `json:"content"`
	MessageCreatedAt time.Time `json:"message_created_at"`
}

type Room struct {
	RoomID           int64     `json:"room_id"`
	RoomCode         string    `json:"room_code"`
	RoomName         *string   `json:"room_name"`
	RoomIsDirectChat bool      `json:"room_is_direct_chat"`
	RoomCreatedBy    uuid.UUID `json:"room_created_by"`
	RoomCreatedAt    time.Time `json:"room_created_at"`
	RoomUpdatedAt    time.Time `json:"room_updated_at"`
}

type RoomMember struct {
	UserUuid            uuid.UUID `json:"user_uuid"`
	RoomID              int64     `json:"room_id"`
	RoomMemberCreatedAt time.Time `json:"room_member_created_at"`
	RoomMemberUpdatedAt time.Time `json:"room_member_updated_at"`
}

type User struct {
	UserUuid      uuid.UUID `json:"user_uuid"`
	UserEmail     string    `json:"user_email"`
	UserPassword  string    `json:"user_password"`
	UserFullname  string    `json:"user_fullname"`
	UserCreatedAt time.Time `json:"user_created_at"`
	UserUpdatedAt time.Time `json:"user_updated_at"`
}
