// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountRoomMessages(ctx context.Context, roomID int64) (int64, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRoom(ctx context.Context, roomID int64) error
	DeleteUser(ctx context.Context, userUuid uuid.UUID) error
	GenerateUniqueRoomCode(ctx context.Context) (string, error)
	GetAllRoomsWithMemberCount(ctx context.Context, arg GetAllRoomsWithMemberCountParams) ([]GetAllRoomsWithMemberCountRow, error)
	GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]User, error)
	GetRoomByCode(ctx context.Context, roomCode string) (Room, error)
	GetRoomByID(ctx context.Context, roomID int64) (Room, error)
	GetRoomMembers(ctx context.Context, roomID int64) ([]User, error)
	GetRoomMessages(ctx context.Context, arg GetRoomMessagesParams) ([]Message, error)
	GetUserByEmail(ctx context.Context, userEmail string) (User, error)
	GetUserByUUID(ctx context.Context, userUuid uuid.UUID) (User, error)
	IsUserMemberOfRoom(ctx context.Context, arg IsUserMemberOfRoomParams) (bool, error)
	JoinRoom(ctx context.Context, arg JoinRoomParams) (RoomMember, error)
	LeaveRoom(ctx context.Context, arg LeaveRoomParams) error
	ListUserRooms(ctx context.Context, userUuid uuid.UUID) ([]Room, error)
	ListUserRoomsWithLastMessage(ctx context.Context, userUuid uuid.UUID) ([]ListUserRoomsWithLastMessageRow, error)
}

var _ Querier = (*Queries)(nil)
